operation:-,accSub
operation:/,accDiv
operation:+,accAdd
operation:/,accDiv
operation:/,accDiv
operation:+,accAdd
operation:/,accDiv
operation:-,accSub
operation:-,accSub
operation:+,accAdd
operation:+,accAdd
operation:+,accAdd