operation:-,accSub
operation:+,accAdd
operation:+=,accAdd
operation:+,accAdd
operation:*,accMul
operation:+,accAdd
operation:-,accSub
operation:+,accAdd
operation:/,accDiv
operation:-,accSub
operation:-,accSub
operation:+=,accAdd
operation:/,accDiv
operation:*,accMul
operation:*,accMul