operation:+,accAdd
operation:*,accMul
operation:+,accAdd
operation:/,accDiv
operation:/,accDiv
operation:+,accAdd
operation:-,accSub
operation:-,accSub
operation:+,accAdd
operation:-,accSub
operation:-,accSub
operation:-,accSub
operation:*,accMul
operation:*,accMul
operation:+,accAdd
operation:/,accDiv
operation:*,accMul
operation:*,accMul
operation:-,accSub
operation:/,accDiv
operation:+=,accAdd
operation:+=,accAdd
operation:*,accMul
operation:/,accDiv
operation:+,accAdd
operation:+,accAdd
operation:+,accAdd
operation:+,accAdd
operation:/,accDiv
operation:/,accDiv
operation:+,accAdd
operation:+,accAdd
operation:+,accAdd
operation:*,accMul
operation:/,accDiv
operation:-,accSub
operation:*,accMul
operation:+,accAdd
operation:+,accAdd
operation:+,accAdd
operation:+,accAdd
operation:+,accAdd
operation:+,accAdd
operation:+=,accAdd
operation:*,accMul
operation:+,accAdd
operation:*,accMul
operation:+,accAdd
operation:*,accMul
operation:*,accMul