operation:-,accSub
operation:+=,accAdd
operation:+,accAdd
operation:/,accDiv
operation:+,accAdd
operation:+,accAdd
operation:+,accAdd
operation:+,accAdd
operation:+,accAdd
operation:+,accAdd
operation:+,accAdd
operation:+,accAdd