operation:-=,accSub
operation:+=,accAdd
operation:-=,accSub
operation:+=,accAdd
operation:-,accSub
operation:*,accMul
operation:+,accAdd
operation:-,accSub
operation:*,accMul
operation:+,accAdd
operation:/,accDiv
operation:*,accMul
operation:-,accSub
operation:*,accMul
operation:+,accAdd
operation:-,accSub
operation:*,accMul
operation:+,accAdd
operation:*,accMul
operation:*,accMul
operation:*,accMul
operation:/,accDiv
operation:/,accDiv
operation:+,accAdd
operation:-,accSub
operation:-,accSub
operation:-,accSub
operation:+,accAdd
operation:+,accAdd
operation:-,accSub
operation:*,accMul
operation:+,accAdd