operation:-,accSub,left:{"type":"MemberExpression","start":1811,"end":1819,"loc":{"start":{"line":25,"column":60},"end":{"line":25,"column":68}},"object":{"type":"Identifier","start":1811,"end":1812,"loc":{"start":{"line":25,"column":60},"end":{"line":25,"column":61},"identifierName":"t"},"name":"t"},"computed":false,"property":{"type":"Identifier","start":1813,"end":1819,"loc":{"start":{"line":25,"column":62},"end":{"line":25,"column":68},"identifierName":"length"},"name":"length"}},right:{"type":"NumericLiteral","start":1822,"end":1823,"loc":{"start":{"line":25,"column":71},"end":{"line":25,"column":72}},"extra":{"rawValue":1,"raw":"1"},"value":1}
start:25,end:25
operation:+,accAdd,left:{"type":"Identifier","start":3907,"end":3919,"loc":{"start":{"line":106,"column":19},"end":{"line":106,"column":31},"identifierName":"operatorName"},"name":"operatorName"},right:{"type":"StringLiteral","start":3922,"end":3925,"loc":{"start":{"line":106,"column":34},"end":{"line":106,"column":37}},"extra":{"rawValue":"/","raw":"\"/\""},"value":"/"}
start:106,end:106
operation:+,accAdd,left:{"type":"CallExpression","callee":{"type":"Identifier","name":"accAdd"},"arguments":[{"type":"Identifier","start":3907,"end":3919,"loc":{"start":{"line":106,"column":19},"end":{"line":106,"column":31},"identifierName":"operatorName"},"name":"operatorName"},{"type":"StringLiteral","start":3922,"end":3925,"loc":{"start":{"line":106,"column":34},"end":{"line":106,"column":37}},"extra":{"rawValue":"/","raw":"\"/\""},"value":"/"}],"trailingComments":[],"leadingComments":[],"innerComments":[]},right:{"type":"Identifier","start":3928,"end":3932,"loc":{"start":{"line":106,"column":40},"end":{"line":106,"column":44},"identifierName":"text"},"name":"text"}
start:106,end:106
operation:+,accAdd,left:{"type":"StringLiteral","start":4701,"end":4751,"loc":{"start":{"line":126,"column":30},"end":{"line":126,"column":80}},"value":"是否确认将公司："},right:{"type":"Identifier","start":4754,"end":4771,"loc":{"start":{"line":126,"column":83},"end":{"line":126,"column":100},"identifierName":"rebateCompanyName"},"name":"rebateCompanyName"}
start:126,end:126
operation:+,accAdd,left:{"type":"CallExpression","callee":{"type":"Identifier","name":"accAdd"},"arguments":[{"type":"StringLiteral","start":4701,"end":4751,"loc":{"start":{"line":126,"column":30},"end":{"line":126,"column":80}},"value":"是否确认将公司："},{"type":"Identifier","start":4754,"end":4771,"loc":{"start":{"line":126,"column":83},"end":{"line":126,"column":100},"identifierName":"rebateCompanyName"},"name":"rebateCompanyName"}],"trailingComments":[],"leadingComments":[],"innerComments":[]},right:{"type":"StringLiteral","start":4774,"end":4909,"loc":{"start":{"line":126,"column":103},"end":{"line":126,"column":238}},"value":" 从黑名单中删除，删除后可正常发起应付或付款？"}
start:126,end:126